name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_screenshot: yes
          plugin_screenshot_title: XKCD of the day  # Section title
          plugin_screenshot_url: https://www.ygktool.cn   # Website url
          plugin_screenshot_selector: "#comic img"  # CSS selector to take into screenshot
          plugin_screenshot_background: no          # Remove page background
